### ISSUE TITLE
Empty array when used with gutils.buffer

### ISSUE THREAD

**Issue by MaxYari** [burnedikt/gulp-scripts-index#1]
Hello there, as subject states.
I tracked down problem to vfs part of your lib. scriptsGlob obj is succesfully filled up with filepaths, but .on("data"..) of vfs is never called. .on("finish"...) is called though, therefore passing ultimately empty file array.

**Comment by burnedikt** [comment]
Sounds like the scripts are all correctly extracted from the html file since the `scriptsGlob` is populated. However, when passing the `scriptsGlob` to `vfs`, `vfs` will only emit the `'data'`-event, whenever one of the globs actually match a file path. 

In this case, probably the globs do not resole to the actual files, which is weird. Can you give me a bit more information like the html-file that you're parsing as well as the folder structure in which the scripts reside?

**Comment by MaxYari** [comment]
Hm makes sense. Will try to check that.
Some quick info: 
my gulpfile is in root
my .html (.ejs in fact) is in ./views (where ./ is root)
my script files are in ./public/scripts

scriptsGlob contain files paths like "D:\webprojects\Appname\views\scripts\app\particleWaves.js"
Haha! Here it is, scripts are under views which is incorrect, now how do i fix it without changing my project  structure hmm

**Comment by MaxYari** [comment]
In ejs sources are like "scripts/app/particleWaves.js"
So it seems it assumes that sources are relative to html, which in case of ejs is a wrong assumption.
Upd: Just figured out that there is a searchPaths thingy... let me try that

**Comment by burnedikt** [comment]
If you're files are located elsewhere, simply use the `searchPaths` parameter to specify additional paths under which the library should check for files. See https://github.com/burnedikt/gulp-scripts-index/blob/master/test/index.js#L78-L88 for an example

**Comment by MaxYari** [comment]
Yep, seems to be working, thanks a lot!
